TabletopSixEcom/urls.py
from django.contrib import admin
from django.urls import path, include
from books.views import redirect_view

urlpatterns = [
    path("", redirect_view),
    path('admin/', admin.site.urls, name="admin_site"),
    path('accounts/', include('allauth.urls')),
    path('books/', include('books.urls')),
    path('reviews/', include('reviews.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
]

books/urls.py
from django.urls import path
import books.views

urlpatterns = [
    path("", books.views.homepage, name="homepage"),
    path("all/", books.views.index, name="show_books"),
    path("create/", books.views.create_book, name="create_book"),
    path("edit_book/<book_id>", books.views.edit_book, name="edit_book"),
    path("delete_book/<book_id>", books.views.delete_book, name="delete_book"),
    path("catsearch/", books.views.get_category, name="cat_search"),
    path("genre_filter/", books.views.genre_filter, name="genre_filter"),
    path("tag_filter/", books.views.tag_filter, name="tag_filter"),
    path("info/<book_id>", books.views.book_info, name="book_info")
]

cart/urls.py
from django.urls import path
from .views import add_to_cart, view_cart, minus_from_cart, remove_from_cart

urlpatterns = [
    path("", view_cart, name="view_cart"),
    path("add/<book_id>", add_to_cart, name="add_to_cart"),
    path("minus/<book_id>", minus_from_cart, name="minus_from_cart"),
    path("remove/<book_id>", remove_from_cart, name="remove_from_cart"),
]

books/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.


def current_year():
    return datetime.date.today().year


def max_value_current_year(value):
    return MaxValueValidator(current_year())(value)


class Book(models.Model):
    title = models.CharField(blank=False, max_length=255)
    ISBN = models.CharField(blank=False, max_length=50)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    release_date = models.PositiveIntegerField(
        default=current_year(),
        validators=[MinValueValidator(1900),
                    max_value_current_year], blank=False)
    price = models.IntegerField(blank=False)
    reviews = models.IntegerField(blank=False)
    cover = CloudinaryField()
    description = models.TextField(blank=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField('Tag')
    genre = models.ForeignKey('Genre', on_delete=models.CASCADE)
    preview_1 = CloudinaryField()
    preview_2 = CloudinaryField()
    preview_3 = CloudinaryField()

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(blank=False, max_length=100)
    publisher = models.CharField(blank=False, max_length=100)

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(blank=False, max_length=50)

    def __str__(self):
        return self.title


class Genre(models.Model):
    title = models.CharField(blank=False, max_length=50)

    def __str__(self):
        return self.title

books/forms.py
from django import forms
from .models import Book, Genre, Tag
from cloudinary.forms import CloudinaryJsFileField


class BookForm(forms.ModelForm):
    choices = ((1, '1 Star'), (2, '2 Stars'),
               (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars'))
    reviews = forms.ChoiceField(choices=choices,
                                widget=forms.RadioSelect(attrs={
                                    'class': 'form-inline'}))
    cover = CloudinaryJsFileField()
    preview_1 = CloudinaryJsFileField()
    preview_2 = CloudinaryJsFileField()
    preview_3 = CloudinaryJsFileField()

    class Meta:
        model = Book
        fields = ('__all__')


class SearchForm(forms.ModelForm):
    title = forms.CharField(max_length=100, required=False)
    genre = forms.ModelChoiceField(
        queryset=Genre.objects.all(), required=False)
    tag = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(), required=False)

books/views.py
from django.shortcuts import (
    render,
    HttpResponse,
    redirect,
    get_object_or_404,
    reverse)
from django.template.loader import render_to_string
from .models import Book, Category, Genre, Tag
from reviews.models import Review
from .forms import BookForm
from reviews.forms import ReviewForm
from django.db.models import Q
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.


def redirect_view(request):
    response = redirect('/books/')
    return response


def homepage(request):
    books = Book.objects.all()
    books_nav = books.order_by('-release_date')[:2]
    books_cut = books.order_by('-release_date')[:10]
    cart = request.session.get('shopping_cart', {})
    grand_total = 0
    for item in cart:
        grand_total += cart[item]['subtotal']
    return render(request, 'books/homepage.template.html', {
        'books': books_cut,
        'books_nav': books_nav,
        'grand_total': grand_total,
    })


def index(request):
    genre = Genre.objects.all()
    tags = Tag.objects.all()
    books_nav = Book.objects.order_by('-release_date')[:2]
    cart = request.session.get('shopping_cart', {})
    grand_total = 0
    for item in cart:
        grand_total += cart[item]['subtotal']

    search_query = request.GET.get('search', '')

    if search_query:
        books = Book.objects.filter(
            Q(title__icontains=search_query) |
            Q(category__title__icontains=search_query) |
            Q(genre__title__icontains=search_query))
    else:
        books_all = Book.objects.all()
        books = books_all.order_by('-release_date')

    return render(request, 'books/index.template.html', {
        'genre': genre,
        'tags': tags,
        'books': books,
        'books_nav': books_nav,
        'grand_total': grand_total,
    })


@login_required
def create_book(request):
    books_nav = Book.objects.order_by('-release_date')[:2]
    cart = request.session.get('shopping_cart', {})
    grand_total = 0
    for item in cart:
        grand_total += cart[item]['subtotal']
    if request.user.is_superuser:
        if request.method == "POST":
            create_form = BookForm(request.POST, request.FILES)
            if create_form.is_valid():
                create_form.save()
                messages.success(
                    request, f"New book {create_form.cleaned_data['title']}"
                    " has been created!")
                return redirect(reverse("homepage"))
            else:
                return render(request, 'books/create_book.template.html', {
                    'form': create_form,
                    'books_nav': books_nav,
                    'grand_total': grand_total,
                })
        else:
            create_form = BookForm
            return render(request, 'books/create_book.template.html', {
                'form': create_form,
                'books_nav': books_nav,
                'grand_total': grand_total,
            })
    else:
        messages.warning(
            request, "You are not administator !"
            " Contact admin to post new products !")
        return redirect(reverse('homepage'))


def edit_book(request, book_id):
    books_nav = Book.objects.order_by('-release_date')[:2]
    cart = request.session.get('shopping_cart', {})
    grand_total = 0
    for item in cart:
        grand_total += cart[item]['subtotal']
    book_to_edit = get_object_or_404(Book, pk=book_id)
    if request.user.is_superuser:
        if request.method == "POST":
            edit_form = BookForm(request.POST, instance=book_to_edit)
            if edit_form.is_valid():
                edit_form.save()
                messages.success(
                    request, f"Book {edit_form.cleaned_data['title']}"
                    f" has been updated!")
                return redirect("book_info", book_id=book_to_edit.id)
            else:
                messages.warning(request, "Invalid update, check form!")
                return render(request, 'books/edit_book.template.html', {
                    'form': edit_form,
                    'books_nav': books_nav,
                    'grand_total': grand_total,
                })
        else:
            edit_form = BookForm(instance=book_to_edit)
            return render(request, 'books/edit_book.template.html', {
                'book': book_to_edit,
                'form': edit_form,
                'books_nav': books_nav,
                'grand_total': grand_total,
            })
    else:
        messages.warning(
            request, "You are not administator !"
            " Contact admin to edit products !")
        return redirect(reverse('homepage'))


def delete_book(request, book_id):
    book_to_delete = get_object_or_404(Book, pk=book_id)
    book_to_delete.delete()
    messages.warning(
        request, f"Book product {book_to_delete.title} has been Deleted !")
    return redirect('show_books')


def get_category(request):
    if request.method == 'GET':
        category_list = Category.objects.all()
        category = []
        for cat in category_list:
            category.append({"id": cat.id, "title": cat.title,
                             "publisher": cat.publisher})
    return JsonResponse(category, safe=False)


def genre_filter(request):
    if request.method == 'GET':
        genre = request.GET.get('text', None)
        genre_filter = Genre.objects.values_list(
            'id', flat=True).get(title=genre)
        data = Book.objects.filter(genre=genre_filter)
        html = render_to_string('books/filtered_data.template.html', {
            "data": data
        })
        return HttpResponse(html)


def tag_filter(request):
    if request.method == 'GET':
        tag = request.GET.get('text', None)
        tag_filter = Tag.objects.values_list(
            'id', flat=True).get(title=tag)
        data = Book.objects.filter(tags=tag_filter)
        html = render_to_string('books/filtered_data.template.html', {
            "data": data
        })
        return HttpResponse(html)


def book_info(request, book_id):
    books = Book.objects.all()
    books_nav = books.order_by('-release_date')[:2]
    cart = request.session.get('shopping_cart', {})
    grand_total = 0
    for item in cart:
        grand_total += cart[item]['subtotal']

    book_selected = get_object_or_404(Book, pk=book_id)
    book_form = BookForm(instance=book_selected)
    review_form = ReviewForm(request.POST)
    reviews = Review.objects.filter(book=book_id)

    if request.method == "POST":
        if request.user.is_authenticated:
            if review_form.is_valid():
                review = review_form.save(commit=False)
                review.user = request.user
                review.book = book_selected
                review.save()
                messages.success(
                    request,
                    f"Review has been posted on {book_selected.title}")
                return redirect('book_info', book_id=book_id)
        else:
            messages.warning(request, "Kindly log in to post reviews !")
            return redirect('account_login')

    return render(request, 'books/book_info.template.html', {
        "books_nav": books_nav,
        "form": book_form,
        "book": book_selected,
        "reviews": reviews,
        "review_form": review_form,
        "grand_total": grand_total,
    })

books/templates/books/create_book.template.html
{% extends 'base.template.html' %}
{% load static %}
{% load cloudinary %}
{% load mathfilters %}
{% load crispy_forms_tags %}

{%block title%}Create New Book{%endblock%}

{%block css%}
<style>
#create_form label{
    color: antiquewhite;
}

#div_id_reviews,
#div_id_cover {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    margin-left: 1rem;
    color: antiquewhite;
}

#div_id_reviews div{
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    align-items: center;
}

#div_id_cover {
    margin-bottom: 0;
}

.status {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    color:antiquewhite;
}
</style>
{%endblock%}

{%block js%}
{% cloudinary_includes %}
{% cloudinary_js_config %}
<script>
$(document).ready(function(){
    $('#id_category').on('change', function(e){
        let bookCategory = $('#id_category').val();
        $.ajax({
            url: "{% url 'cat_search' %}",
            dataType: "json",
            type: "GET",
            success: function(data){
                for (let i = 0; i < data.length; i++){
                    if (bookCategory == data[i].id){
                        $('#form_publisher').val(data[i].publisher)
                    }
                }

            }
        })
    });

    function prettydump(obj) {
    ret = ""
    $.each(obj, function(key, value) {
        ret += "<tr><td>" + key + "</td><td>" + value + "</td></tr>";
    });
    return ret;
    }

    $('#cover input[type="file"]')
    .cloudinary_fileupload({
        dropZone: '#cover',
        start: function () {
        $('#cover_status_value').text('Starting direct upload...');
        },
        progress: function () {
        $('#cover_status_value').text('Uploading...');
        },
    })
    .on('cloudinarydone', function (e, data) {
        $('#cover_status_value').text('Updating backend... submit to complete...');
        var info = $('<div class="uploaded_info"/>');
        $(info).append($('<div class="image d-flex justify-content-center"/>').append(
            $.cloudinary.image(data.result.public_id, {
            format: data.result.format, width: 150, height: 200, crop: "fit"
            })
        ));
        $('#cover').append(info);
        $('#cover input[type="file"]').parent().parent().remove();
        });

    
    $('#preview1 input[type="file"]')
    .cloudinary_fileupload({
        dropZone: '#preview1',
        start: function () {
        $('#preview1_status_value').text('Starting direct upload...');
        },
        progress: function () {
        $('#preview1_status_value').text('Uploading...');
        },
    })
    .on('cloudinarydone', function (e, data) {
        $('#preview1_status_value').text('Updating backend... submit to complete...');
        var info1 = $('<div class="uploaded_info_1"/>');
        $(info1).append($('<div class="image d-flex justify-content-center"/>').append(
            $.cloudinary.image(data.result.public_id, {
            format: data.result.format, width: 150, height: 200, crop: "fit"
            })
        ));
        $('#preview1').append(info);
        $('#preview1 input[type="file"]').parent().parent().remove();
        });

    $('#preview2 input[type="file"]')
    .cloudinary_fileupload({
        dropZone: '#preview2',
        start: function () {
        $('#preview2_status_value').text('Starting direct upload...');
        },
        progress: function () {
        $('#preview2_status_value').text('Uploading...');
        },
    })
    .on('cloudinarydone', function (e, data) {
        $('#preview2_status_value').text('Updating backend... submit to complete...');
        var info1 = $('<div class="uploaded_info"/>');
        $(info1).append($('<div class="image d-flex justify-content-center"/>').append(
            $.cloudinary.image(data.result.public_id, {
            format: data.result.format, width: 150, height: 200, crop: "fit"
            })
        ));
        $('#preview2').append(info);
        $('#preview2 input[type="file"]').parent().parent().remove();
        });    
    
    $('#preview3 input[type="file"]')
    .cloudinary_fileupload({
        dropZone: '#preview3',
        start: function () {
        $('#preview3_status_value').text('Starting direct upload...');
        },
        progress: function () {
        $('#preview3_status_value').text('Uploading...');
        },
    })
    .on('cloudinarydone', function (e, data) {
        $('#preview3_status_value').text('Updating backend... submit to complete...');
        var info1 = $('<div class="uploaded_info"/>');
        $(info1).append($('<div class="image d-flex justify-content-center"/>').append(
            $.cloudinary.image(data.result.public_id, {
            format: data.result.format, width: 150, height: 200, crop: "fit"
            })
        ));
        $('#preview3').append(info);
        $('#preview3 input[type="file"]').parent().parent().remove();
        });


})
</script>
{%endblock%}

{%block content%}
<div class="container-fluid">
    <div class="container d-flex flex-column justify-content-center align-items-center" id="form">
        <h2 class="my-5 text-center col-md-12">Create a NEW Book Product</h2>
        <form method="POST" class="col-md-8" id="create_form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row mb-2">
                <div class="form-group col-md-6 mb-0">
                    {{ form.title|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.ISBN|as_crispy_field }}
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-4 mb-0">
                    <label for="form_publisher" class="requiredField">Publisher</label>
                    <input class="form-control" type="text" id="form_publisher" readonly>
                </div>
                <div class="form-group col-md-4 mb-0">
                    {{ form.category|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0">
                    {{ form.release_date|as_crispy_field }}
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-6 mb-0">
                    {{ form.price|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0" id="cover">
                    {{ form.cover|as_crispy_field }}
                    <small id="cover_text" class="form-text text-muted">
                        <div class="status ml-3 my-0">
                            <h6>Status</h6><span id="cover_status_value">Idle</span>
                        </div>
                    </small>
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-6 mb-0">
                    {{ form.tags|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.genre|as_crispy_field }}
                    {{ form.owner|as_crispy_field }}
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-12 mb-0">
                    {{ form.reviews|as_crispy_field }}
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-12 mb-0">
                    {{ form.description|as_crispy_field }}
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-4 mb-0" id="preview1">
                    {{ form.preview_1|as_crispy_field }}
                    <small id="preview1_text" class="form-text text-muted">
                        <div class="status ml-3 my-0">
                            <h6>Status</h6><span id="preview1_status_value">Idle</span>
                        </div>
                    </small>
                </div>
                <div class="form-group col-md-4 mb-0 preview_2" id="preview2">
                    {{ form.preview_2|as_crispy_field }}
                <small class="form-text text-muted">
                    <div class="status ml-3 my-0">
                        <h6>Status</h6><span id="preview2_status_value">Idle</span>
                    </div>
                </small>
                </div>
                <div class="form-group col-md-4 mb-0" id="preview3">
                    {{ form.preview_3|as_crispy_field }}
                    <small class="form-text text-muted">
                        <div class="status ml-3 my-0">
                            <h6>Status</h6><span id="preview3_status_value">Idle</span>
                        </div>
                    </small>
                </div>
            </div>
            <div class="form-row mb-5">
                <div class="form-group col-md-12 mb-0 d-flex justify-content-center align-items-center">
                    <input type="submit" class="btn btn-lg btn-outline-primary">
                </div>
            </div>
        </form>
    </div>
</div>

{%endblock%}

books/templates/books/edit_book.template.html
{% extends 'base.template.html' %}
{% load static %}
{% load cloudinary %}
{% load mathfilters %}
{% load crispy_forms_tags %}

{%block title%}Edit {{book.title}} Book{%endblock%}

{%block css%}<link rel="stylesheet" href="{% static '/css/edit_book.css' %}">{%endblock%}

{%block js%}
{% cloudinary_includes %}
{% cloudinary_js_config %}
<script>
$(document).ready(function(){
    $('#id_category').on('change', function(e){
        let bookCategory = $('#id_category').val();
        $.ajax({
            url: "{% url 'cat_search' %}",
            dataType: "json",
            type: "GET",
            success: function(data){
                for (let i = 0; i < data.length; i++){
                    if (bookCategory == data[i].id){
                        $('#form_publisher').val(data[i].publisher)
                    }
                }

            }
        })
    });

    function prettydump(obj) {
    ret = ""
    $.each(obj, function(key, value) {
        ret += "<tr><td>" + key + "</td><td>" + value + "</td></tr>";
    });
    return ret;
    }

    $('#cover input[type="file"]')
    .cloudinary_fileupload({
        dropZone: '#cover',
        start: function () {
        $('#cover_status_value').text('Starting direct upload...');
        },
        progress: function () {
        $('#cover_status_value').text('Uploading...');
        },
    })
    .on('cloudinarydone', function (e, data) {
        $('#cover_status_value').text('Updating backend... submit to complete...');
        var info = $('<div class="uploaded_info"/>');
        $(info).append($('<div class="image d-flex justify-content-center"/>').append(
            $.cloudinary.image(data.result.public_id, {
            format: data.result.format, width: 150, height: 200, crop: "fit"
            })
        ));
        $('#cover').append(info);
        $('#cover input[type="file"]').parent().parent().remove();
        });

    
    $('#preview1 input[type="file"]')
    .cloudinary_fileupload({
        dropZone: '#preview1',
        start: function () {
        $('#preview1_status_value').text('Starting direct upload...');
        },
        progress: function () {
        $('#preview1_status_value').text('Uploading...');
        },
    })
    .on('cloudinarydone', function (e, data) {
        $('#preview1_status_value').text('Updating backend... submit to complete...');
        var info = $('<div class="uploaded_info_1"/>');
        $(info).append($('<div class="image d-flex justify-content-center"/>').append(
            $.cloudinary.image(data.result.public_id, {
            format: data.result.format, width: 150, height: 200, crop: "fit"
            })
        ));
        $('#preview1').append(info);
        $('#preview1 input[type="file"]').parent().parent().remove();
        });

    $('#preview2 input[type="file"]')
    .cloudinary_fileupload({
        dropZone: '#preview2',
        start: function () {
        $('#preview2_status_value').text('Starting direct upload...');
        },
        progress: function () {
        $('#preview2_status_value').text('Uploading...');
        },
    })
    .on('cloudinarydone', function (e, data) {
        $('#preview2_status_value').text('Updating backend... submit to complete...');
        var info = $('<div class="uploaded_info"/>');
        $(info).append($('<div class="image d-flex justify-content-center"/>').append(
            $.cloudinary.image(data.result.public_id, {
            format: data.result.format, width: 150, height: 200, crop: "fit"
            })
        ));
        $('#preview2').append(info);
        $('#preview2 input[type="file"]').parent().parent().remove();
        });    
    
    $('#preview3 input[type="file"]')
    .cloudinary_fileupload({
        dropZone: '#preview3',
        start: function () {
        $('#preview3_status_value').text('Starting direct upload...');
        },
        progress: function () {
        $('#preview3_status_value').text('Uploading...');
        },
    })
    .on('cloudinarydone', function (e, data) {
        $('#preview3_status_value').text('Updating backend... submit to complete...');
        var info = $('<div class="uploaded_info"/>');
        $(info).append($('<div class="image d-flex justify-content-center"/>').append(
            $.cloudinary.image(data.result.public_id, {
            format: data.result.format, width: 150, height: 200, crop: "fit"
            })
        ));
        $('#preview3').append(info);
        $('#preview3 input[type="file"]').parent().parent().remove();
        }); 

})
</script>
{%endblock%}

{%block content%}
<div class="container-fluid">
    <div class="container d-flex flex-column justify-content-center align-items-center" id="form">
        <h2 class="my-5 text-center col-md-12">Editing {{book.title}} Book</h2>
        <form method="POST" class="col-md-8" id="create_form" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-row mb-2">
                <div class="form-group col-md-6 mb-0">
                    {{ form.title|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.ISBN|as_crispy_field }}
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-4 mb-0">
                    <label for="form_publisher" class="requiredField">Publisher</label>
                    <input class="form-control" type="text" id="form_publisher" readonly>
                </div>
                <div class="form-group col-md-4 mb-0">
                    {{ form.category|as_crispy_field }}
                </div>
                <div class="form-group col-md-4 mb-0">
                    {{ form.release_date|as_crispy_field }}
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-6 mb-0">
                    {{ form.price|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0 form_line" id="cover">
                    {{ form.cover|as_crispy_field }}
                    <small id="cover_text" class="form-text text-muted">
                        <div class="status ml-3 my-0">
                            <h6>Status</h6><span id="cover_status_value">Idle</span>
                        </div>
                    </small>
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-6 mb-0">
                    {{ form.tags|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.genre|as_crispy_field }}
                    {{ form.owner|as_crispy_field }}
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-12 mb-0">
                    {{ form.reviews|as_crispy_field }}
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-12 mb-0">
                    {{ form.description|as_crispy_field }}
                </div>
            </div>
            <div class="form-row mb-2">
                <div class="form-group col-md-4 mb-0 form_line" id="preview1">
                    {{ form.preview_1|as_crispy_field }}
                    <small id="preview1_text" class="form-text text-muted">
                        <div class="status ml-3 my-0">
                            <h6>Status</h6><span id="preview1_status_value">Idle</span>
                        </div>
                    </small>
                </div>
                <div class="form-group col-md-4 mb-0 form_line" id="preview2">
                    {{ form.preview_2|as_crispy_field }}
                <small class="form-text text-muted">
                    <div class="status ml-3 my-0">
                        <h6>Status</h6><span id="preview2_status_value">Idle</span>
                    </div>
                </small>
                </div>
                <div class="form-group col-md-4 mb-0 form_line" id="preview3">
                    {{ form.preview_3|as_crispy_field }}
                    <small class="form-text text-muted">
                        <div class="status ml-3 my-0">
                            <h6>Status</h6><span id="preview3_status_value">Idle</span>
                        </div>
                    </small>
                </div>
            </div>
            <div class="form-row mb-5">
                <div class="form-group col-md-12 mb-0 d-flex justify-content-center align-items-center">
                    <a href="{% url 'show_books' %}" class="btn btn-lg btn-outline-warning mx-3">Cancel</a>
                    <input type="submit" class="btn btn-lg btn-outline-primary mx-3">
                </div>
            </div>
        </form>
    </div>
</div>

{%endblock%}

books/templates/books/filtered_data.template.html
{% load cloudinary %}
{% load mathfilters%}

{% for book in data %}
    <div class="homebooks mx-3 mb-3">
        <button class="p-0" data-html="true" data-toggle="popover" data-trigger="focus" title="{{book.category}}<hr>{{book.title}}" data-content="ISBN: {{book.ISBN}}<br/>Release: {{book.release_date}}<br/>Ratings: {{book.reviews}} / 5">
            {% cloudinary book.cover width=150 height=225 crop="fill" alt="book cover image"%}
        </button>
        <div class="homebooks_text d-flex flex-row justify-content-between align-items-center p-0 mb-3">
            <p class="m-0 pl-2">Price: ${{book.price|div:100}}</p>
            <a href="{% url 'book_info' book_id=book.id %}" class="btn btn-sm btn-info">Buy</a>
        </div>
    </div>
{% endfor %}

<style>
.homebooks {
    width: 155px;
    height: auto;
}

.homebooks_text{
    color: antiquewhite;
    background-color: rgba(0,0,0,1);
    font-size: 0.8rem;
}
.homebooks_text a {
    font-size: 0.8rem;
}

.popover-header {
    font-size: 0.8rem;
    text-align: center;
    background: rgba(25,25,25,1);
    border: solid 1px antiquewhite;
}

.popover-header hr {
    border-color: antiquewhite;
}

.popover-body {
    font-size: 0.7rem;
    font-weight: bold;
    background:  rgba(178, 190, 181,1)
}
</style>

<script>
// Bootstrap 4 Popover Script
$(function () {
  $('[data-toggle="popover"]').popover()
})
$('.popover-dismiss').popover({
  trigger: 'focus'
})
</script>